### ISSUE TITLE
Default retryDelay is 0.01

### ISSUE THREAD

**Issue by God-damnit-all** [fake-name/WebRequest#2]
Default retryDelay is 0.01. That's almost guaranteed to give someone's cloudflare fits the moment something doesn't load.

**Comment by God-damnit-all** [comment]
P.S. Your unique spelling of the word 'retrieval' makes it pretty easy to figure out your alt account.

**Comment by fake-name** [comment]
> P.S. Your unique spelling of the word 'retrieval' makes it pretty easy to figure out your alt account.

Lol. I'm not exactly trying.

**Comment by God-damnit-all** [comment]
You alive? I've been submitting stuff on the other project.

**Comment by fake-name** [comment]
Yes? Pretty sure I even [merged some of your changes.](https://github.com/herp-a-derp/xA-Scraper/pull/43).

Also, this is fixed in [3d83f1e44bf5904d10637b3765b03a51e676a7a6](https://github.com/fake-name/WebRequest/commit/3d83f1e44bf5904d10637b3765b03a51e676a7a6#diff-40853d2918c8f9937455cb6cafa40b59)

**Comment by fake-name** [comment]
Basically, I've been dealing with some stupid issues with the anti-captcha reverse proxy server automatic spinup. I need that to deal with the patreon stuff, and I've been focusing on that (and my day-job) recently. 

OTOH, I think I finally got it working last night.

**Comment by God-damnit-all** [comment]
On the subject of Patreon, they recently added a new type of multi-image gallery feature that the more online-based scraper doesn't detect properly. Only downloads the first image from them. Based on that evidence, your code might require a backend change to properly support it.

**Comment by fake-name** [comment]
Considering the patreon module is basically completely fucked ATM, that's probably a safe assumption.
